(function(){
    window.IBQuestions = [
        "If you could live in a book, TV show, or movie, what would it be?",
        "How would you spend a billion dollars?",
        "Why did you choose your profession?",
        "What is Craig's favourite type of cheese?",
        "Why does mom hate me?",
        "Why do i exist?",
        "PLEASE MAKE IT STOP?",
        "In what ways do you hold yourself back?",
        "What did you get detention for when you were in school?",
        "If you could get away with a crime, would you? What would it be?",
        "What animal best represents you and why?",
        "What sport or activity did you do in school?",
        "How do you want to be remembered?",
        "What do you spend most of your money on?",
        "Would you rather live in the city or the woods?",
        "What's your favorite comedy?",
        "If you could travel anywhere in the world, where would it be?",
        "If you could live forever, would you? How would you spend eternity?",
        "What message would you choose to send to an advanced alien species?",
        "What three emoji describe you best?",
        "What fad do you wish would come back? Which do you feel should stay gone forever?",
        "What's your favorite dish to cook?",
        "If it were possible have a pet dinosaur, what dinosaur would you want?",
        "What's the best concert you've ever attended?",
        "What dream have you had that still resonates with you?",
        "Which are you more likely to fight for, love or money? Why?",
        "If you could change one law, what would it be?",
        "Would you rather explore the bottom of the ocean or a new planet?",
        "What's the most traumatic movie or book you saw/read as a child?",
        "Describe your family in a nutshell.",
        "If you could bring one fictional character to life, who would it be and why?",
        "If you could time travel, would you go to the past or future?",
        "What would be your perfect day?",
        "What is your favorite childhood book?",
        "If you could choose your last words, what would they be?",
        "If you had a theme song, what would it be?",
        "If you could change one event from history, what would it be?",
        "What unusual skills do you have?",
        "Who is your dream dinner guest?",
        "If you could master one skill you don't have right now, what would it be?",
        "What hobby or activity are you into?",
        "If you could speak to everyone in the world at the same time, what would you say?",
        "What celebrities did you have a crush on as a kid?",
        "What's something your grandparents taught you?",
        "What is the worst fad you participated in?",
        "Do you have any tattoos? What is the story behind them?",
        "If you could live in any 1900s era, which one would you choose?",
        "What is your greatest strength?",
        "What book did you last read? What did you think?",
        "For what in your life do you feel most grateful?",
        "What advice would you give to yourself at 13 years old?",
        "What's your life story in one minute or less?",
        "What is your go-to karaoke song? Extra points for singing part of it.",
        "Who are you dying to see in concert?",
        "What was your best Halloween costume ever?",
        "What is one item from your bucket list?",
        "What's your favorite holiday?",
        "Are you spiritual, religious, agnostic, athiest? What does spirituality mean to you?",
        "What show are you watching now?",
        "Who's your personal hero?",
        "What is one of the most spontaneous things you've ever done?",
        "How did your parents meet?",
        "What did you want to be when you grew up?",
        "What's a fact about you that surprises people?",
        "What are you irrationally afraid of?",
        "What was the last movie you went to? What did you think?",
        "Do you know any good ghost stories?",
        "Do you like or dislike surprises? Why or why not?",
        "What was your closest near-death experience?",
        "What book or TV show changed your life?",
        "Is there something that you've dreamt of doing for a long time? Why haven't you done it?",
        "What was your first job?",
        "Name a gift you will never forget.",
        "What's the weirdest thing you've ever eaten?"
    ];
})();
